dota2_team_picker_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from django.conf.urls import (
handler400, handler403, handler404, handler500
)
handler404 = 'teampicker.views.handler404'


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^teampicker/', include('teampicker.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
)

teampicker/urls.py
from django.conf.urls import patterns, url
from teampicker import views

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^test/$', views.test, name='test'),
        url(r'^about/$', views.about, name='about'),
        url(r'^users/$', views.userlist, name='userlist'),
        url(r'^users/(?P<user_username>[\w\-]+)/$', views.user, name='user'),
        url(r'^editaccount/$', views.editUser, name='editUser'),
        url(r'^teams/$', views.teamList, name='teamList'),
        url(r'^teams/(?P<team_slug>[\w\-]+)/$', views.teamView, name='team'),
        url(r'^teams/(?P<team_slug>[\w\-]+)/edit/$', views.editTeam, name='editTeam'),
        url(r'^search/$', views.search, name="search"),
        
        )
        

teampicker/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from vote.managers import VotableManager
from django.utils import timezone

class Hero(models.Model):
    name = models.CharField(max_length=128, unique=True)
    image = models.CharField(max_length=128, default="")
    type = models.CharField(max_length=128, default="")
    

    def __unicode__(self):  #For Python 2, use __str__ on Python 3
        return self.name
        

class Team(models.Model):
    name = models.CharField(max_length=128, default="")
    description = models.CharField(max_length=128, default="")        
    slug = models.SlugField(unique=True)
    user = models.ForeignKey(User, related_name='team', default="")
    votes = VotableManager()
    voteCount = models.IntegerField(default="0")
    roster = models.CharField(max_length=300, default="")
    created     = models.DateTimeField(default=timezone.now, editable=False)
    modified    = models.DateTimeField(default=timezone.now)

    def updateVoteCount(self):
        self.voteCount = self.votes.count()

    #save function
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        if not self.id:
            self.created = timezone.now()
        self.modified = timezone.now()
        super(Team, self).save(*args, **kwargs)
    
    def __unicode__(self):  #For Python 2, use __str__ on Python 3
        return self.name
        

teampicker/forms.py
from django import forms
from django.contrib.auth.models import User
from teampicker.models import Team

class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'last_name', 'username']
        
        
class AddNewTeamForm(forms.ModelForm):
    name = forms.CharField(max_length=128, widget=forms.TextInput(attrs={'type' : 'text', 'class' : 'form-control', 'placeholder' : 'Name'}))
    description = forms.CharField(max_length=128, widget=forms.TextInput(attrs={'type' : 'text', 'class' : 'form-control', 'placeholder' : 'A description for your team...'}))
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    roster = forms.CharField(widget=forms.HiddenInput(), required=False)
    
    class Meta:
        model = Team
        fields = ['name', 'description', 'roster']
        exclude = ('user',)
        
        
class UpdateTeamForm(forms.ModelForm):
    roster = forms.CharField(widget=forms.HiddenInput(), required=False)
    class Meta:
        model = Team
        fields = ['name', 'description', 'roster']

teampicker/views.py
from django.shortcuts import render
from django.http import HttpResponse
from teampicker.models import Hero
from teampicker.models import Team
from django.contrib.auth.models import User
from teampicker.forms import UpdateUserForm
from teampicker.forms import AddNewTeamForm
from teampicker.forms import UpdateTeamForm

from django.shortcuts import render_to_response
from django.template import RequestContext

from django.db.models import Q

def index(request):

    context_dict = {}
    
    heroes = Hero.objects.all()
    
    context_dict["heroes"] = heroes
    rowLength = 10
    context_dict["rowLength"] = rowLength
    
    
    teams = Team.objects.all()
    for team in teams:
        team.updateVoteCount()
        team.save()

    highlyRatedTeams = Team.objects.order_by('-voteCount')[:5]
    context_dict['highlyRated'] = highlyRatedTeams

    recentlyCreatedTeams = Team.objects.order_by('-created')[:5]
    context_dict['recentlyCreated'] = recentlyCreatedTeams

    if request.method == "POST":
        form = AddNewTeamForm(data=request.POST)
        if form.is_valid():
            team = form.save(commit=False)
            team.user = request.user
            team.save() 
            context_dict["form"] = form
            return teamView(request, team.name)
    else:
        form = AddNewTeamForm()
        context_dict["form"] = form
            
    if request.method == "GET":
        if 'clear' in request.GET:
            heroes = Hero.objects.all()
            context_dict["heroes"] = heroes  
        if 'carry' in request.GET:
            heroes = Hero.objects.filter(type__icontains="Carry")
            context_dict["heroes"] = heroes  
        if 'support' in request.GET:
            heroes = Hero.objects.filter(type__icontains="Support")
            context_dict["heroes"] = heroes        
        if 'laneSupport' in request.GET:
            heroes = Hero.objects.filter(type__icontains="Lane Support")
            context_dict["heroes"] = heroes      
        if 'disabler' in request.GET:
            heroes = Hero.objects.filter(type__icontains="Disabler")
            context_dict["heroes"] = heroes      
        if 'initiator' in request.GET:
            heroes = Hero.objects.filter(type__icontains="Initiator")
            context_dict["heroes"] = heroes      
        if 'pusher' in request.GET:
            heroes = Hero.objects.filter(type__icontains="Pusher")
            context_dict["heroes"] = heroes              
        if 'durable' in request.GET:
            heroes = Hero.objects.filter(type__icontains="Durable")
            context_dict["heroes"] = heroes               
        if 'nuker' in request.GET:
            heroes = Hero.objects.filter(type__icontains="Nuker")
            context_dict["heroes"] = heroes              
        if 'escape' in request.GET:
            heroes = Hero.objects.filter(type__icontains="Escape")
            context_dict["heroes"] = heroes              
        if 'jungler' in request.GET:
            heroes = Hero.objects.filter(type__icontains="Jungler")
            context_dict["heroes"] = heroes     
            
    
    return render(request, 'teampicker/index.html', context_dict)
    

def test(request):
    
    context_dict = {}
    
    heroes = Hero.objects.all()
    
    context_dict["heroes"] = heroes
    
    return render(request, 'teampicker/test.html', context_dict)    
    

def about(request):
    return render(request, 'teampicker/about.html')
    
 
def user(request, user_username):
    context_dict = {}

    try:
        user = User.objects.get(username=user_username)
        context_dict['thisUser'] = user.username
        context_dict['lastLogin'] = user.last_login
        context_dict['dateJoined'] = user.date_joined
        
        teams = Team.objects.filter(user=user)
        context_dict['teams'] = teams
        
        if user == request.user:
            context_dict['ownAccount'] = 1

    except User.DoesNotExist:
        pass

    return render(request, 'teampicker/user.html', context_dict)
    
    
def userlist(request):
    context_dict = {}
    
    userList = User.objects.all()
    context_dict['users'] = userList
    
    return render(request, 'teampicker/userlist.html', context_dict)    
    
    
def editUser(request):
    context_dict = {}
    
    try:
        user = request.user
        context_dict['thisUser'] = user.username
        context_dict['email'] = user.email
        
        
        if request.method == "POST":
            form = UpdateUserForm(data=request.POST, instance=request.user)
            if form.is_valid():
                user = form.save(commit=False)
                user.save()
                
                context_dict["form"] = form
                
                context_dict['thisUser'] = user.username
                context_dict['email'] = user.email
        else:
            form = UpdateUserForm(instance=request.user)
            context_dict["form"] = form
            
    except User.DoesNotExist:
        pass

    return render(request, 'teampicker/edituser.html', context_dict)    
    

def teamList(request):
    context_dict = {}
    
    context_dict['teams'] = Team.objects.all()
    
    return render(request, 'teampicker/teamlist.html', context_dict)    
    
    
def teamView(request, team_slug):
    context_dict = {}
    
    try:
        team = Team.objects.get(slug=team_slug)
        context_dict['teamSlug'] = team.slug
        context_dict['teamName'] = team.name
        context_dict['teamDescription'] = team.description
        context_dict['dateCreated'] = team.created
        context_dict['dateModified'] = team.modified
        
        try:
            roster1 = team.roster.split(",")
            theRoster = []
            for x in range(0, len(roster1)):
                theRoster.append(Hero.objects.get(name=roster1[x]))
                
            context_dict['theRoster'] = theRoster
        except:
            pass
            
        context_dict['count'] = team.votes.count
        
        user = team.user
        context_dict['theUser'] = user
        
        if user == request.user:
            context_dict['ownTeam'] = 1
        
        if request.method == "GET":
            if request.user.is_authenticated():
                context_dict['voted'] = team.votes.exists(request.user)
            
                if 'voteUp' in request.GET:
                    if not team.votes.exists(request.user):
                        team.votes.up(request.user)
                        context_dict['votedUp'] = "1"
                        
                if 'voteDown' in request.GET:
                    team.votes.down(request.user)
                    
                if 'delete' in request.GET:
                    team.delete();    
                    return teamList(request)
                    
                    
                if team.votes.exists(request.user):
                    context_dict['votedUp'] = "1"
            
    except Team.DoesNotExist:
        pass
    
    return render(request, 'teampicker/team.html', context_dict)    
    
    
def handler404(request):
    response = render_to_response('teampicker/404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response
    
    
def search(request):
    context_dict = {}

    context_dict['query'] = "Search for users or team builds"

    if 'q' in request.GET:
        q = request.GET.get('q')
        try: 
            teams = Team.objects.filter(Q(name__icontains=q) | Q(slug__icontains=q))
            users = User.objects.filter(username__icontains=q)
            
            context_dict['teams'] = teams
            context_dict['users'] = users
            context_dict['query'] = q

            return render(request, 'teampicker/search.html', context_dict)

        except:  
            return render(request, 'teampicker/search.html', context_dict)

    return render(request, 'teampicker/search.html', context_dict)    
    

def editTeam(request, team_slug):
    context_dict = {}

    team = Team.objects.get(slug=team_slug)
    
    heroes = Hero.objects.all()
    
    context_dict["heroes"] = heroes
    rowLength = 10
    context_dict["rowLength"] = rowLength
    
    
   
    
    try:
        if request.method == "POST":
            form = UpdateTeamForm(data=request.POST, instance=team)
            if form.is_valid():
                team = form.save(commit=False)
                team.save()
                
                context_dict["form"] = form
                
        else:
            form = UpdateTeamForm(instance=team)
            context_dict["form"] = form
                
    except:
        pass
        
        
    try:
        roster1 = team.roster.split(",")
        theRoster = []
        for x in range(0, len(roster1)):
            theRoster.append(Hero.objects.get(name=roster1[x]))
            
        context_dict['theRoster'] = theRoster
    except:
        pass    

    context_dict['teamSlug'] = team.slug
    context_dict['teamName'] = team.name
    context_dict['teamDescription'] = team.description
    

    return render(request, 'teampicker/editteam.html', context_dict)

templates/teampicker/about.html
{% extends 'teampicker/base.html' %}
{% load staticfiles %}

{% block title %}Dota 2 Team Picker - About{% endblock %}

{% block body_block %}
    <div class="container-fluid">
        <div class="row">
            <h1>about</h1>            
        </div>   
    </div>
{% endblock %}

templates/teampicker/editteam.html
{% extends 'teampicker/base.html' %}
{% load staticfiles %}



{% block title %}Dota 2 Team Picker - Edit Team{% endblock %}

{% block body_block %}
    <div class="container-fluid">
        <div class="row">
                  
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">{{ teamName }}</h3>
                    </div>
                    <div class="panel-body">
                    
                        <div class="row">
                        
                            <form class="form-horizontal" role="form" method="POST" action=".">
                                {% csrf_token %}

                                
                                         

                                <div class="form-group">
                                    <label for="id_username" class="col-sm-2 control-label">Team Name</label>
                                    <div class="col-sm-6">
                                    <input type="text" class="form-control" id="id_name" name="name" placeholder="{{ teamName }}">
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label for="id_email" class="col-sm-2 control-label">Description</label>
                                    <div class="col-sm-6">
                                    <input type="text" class="form-control" id="id_description" name="description" placeholder="{{ teamDescription }}">
                                    </div>
                                </div>
                                
                                             {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
                                
                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-primary">Save Changes</button>
                                    </div>
                                </div>
                            </form>
                        
                        </div>
                    </div>
                    
                    <table class="table text-center" id="team">
                        <tr>
                            {% for hero in theRoster %}
                        <td>
                            <input type="image" src="{% static hero.image %}" onclick="testFunc2(this)" data-toggle="popover" data-trigger="hover" title="{{ hero.name }}" data-html="true" data-content="{{ hero.type }}" width="127" height="71" border="1"></src>
                        </td>
                        {% endfor %}
                        </tr>
                        </table>
                    
                </div>
                
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Hero Roster</h3>
                    </div>
                    <div class="panel-body">

                    </div>
                    <table class="table table-striped table-condensed text-center" id="heroes">
                        {% for hero in heroes %}
                        <td padding="10px">
                        <p><input type="image" src="{% static hero.image %}" onclick="testFunc(this)" data-toggle="popover" data-trigger="hover" title="{{ hero.name }}" data-html="true" data-content="{{ hero.type }}" width="63" height="35" border="1"></src>
                        </td>
                            {% if forloop.counter|divisibleby:10 %}
                                <tr></tr>
                            {% endif %}
                        {% endfor %}
                    </table>
                </div>
                
            </div>
                     
        </div>   
        
        
       
    </div>
{% endblock %}

templates/teampicker/index.html
{% extends 'teampicker/base.html' %}
{% load staticfiles %}

{% block title %}Dota 2 Team Picker{% endblock %}

{% block body_block %}
    <div class="container-fluid">
        <div class="row">

            <div class="col-md-8 col-md-offset-2">

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Your Team</h3>
                    </div>
                    <div class="panel-body">
                        {% if user.is_authenticated %}
                            <input class="btn btn-default" type="button" onclick="clearTeam()" value="Clear Team" />
                            <!-- Button trigger modal -->
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                            Save Team
                            </button>

                            <!-- Modal -->
                            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title" id="myModalLabel">Save a Team Build</h4>
                                        </div>
                                        <div class="modal-body">
                                            <form role="form" method="POST" action="">
                                                {% csrf_token %}
                                                <div class="form-group">
                                                        <label for="id_name">Team Name</label>
                                                        {{ form.name }}
                                                </div>
                                                    
                                                <div class="form-group">
                                                        <label for="id_description">Description</label>
                                                        {{ form.description }}
                                                </div>
                                                
                                                {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-primary">Save Team</button>
                                            </form>
                                        </div>      
                                    </div>
                                </div>
                            </div>         
                        {% else %}
                            <input class="btn btn-default" type="button" onclick="clearTeam()" value="Clear Team" />
                            <!-- Button trigger modal -->
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                            Save Team
                            </button>

                            <!-- Modal -->
                            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title" id="myModalLabel">Save a Team Build</h4>
                                        </div>
                                        <div class="modal-body">
                                            <div class="row">
                                                <div class="col-md-8 col-md-offset-2">
                                                    
                                                    <form class="form-signin" role="form" method="post" action="{% url 'auth_login' %}"">
                                                        {% csrf_token %}

                                                        <p>You must be logged in to save a team build.</p>
                                                        <input class="form-control" placeholder="Username" id="id_username" maxlength="254" name="username" type="text" required autofocus=""/>
                                                        <input type="password" class="form-control" placeholder="Password" id="id_password" name="password"  required />

                                                        <button class="btn btn-primary btn-lg btn-block" type="submit" value="Submit" >Sign In</button>
                                                        <br>                
                                                        <p>Not  a member? <a href="{% url 'registration_register' %}">Sign up!</a></p>
                                                    </form>
                                                    
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div> 
                        {% endif %}         
                    </div>

                    <table class="table text-center" id="team">
                        <tr>
                        </tr>
                    </table>
                </div>
                
                

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Hero Roster</h3>
                    </div>
                    <div class="panel-body">
                    
                        <div class="btn-group" role="group" aria-label="...">
                                
                            <form role="form" method="GET" action="">
                                {% csrf_token %}
                                <input type="submit" type="button" class="btn btn-primary" name="clear" value="Clear"></input>
                                <input type="submit" type="button" class="btn btn-primary" name="carry" value="Carry"></input>
                                <input type="submit" type="button" class="btn btn-primary" name="support" value="Support"></input>
                                <input type="submit" type="button" class="btn btn-primary" name="laneSupport" value="Lane Support"></input>
                                <input type="submit" type="button" class="btn btn-primary" name="disabler" value="Disabler"></input>
                                <input type="submit" type="button" class="btn btn-primary" name="initiator" value="Initiator"></input>
                                <input type="submit" type="button" class="btn btn-primary" name="pusher" value="Pusher"></input>
                                <input type="submit" type="button" class="btn btn-primary" name="durable" value="Durable"></input>
                                <input type="submit" type="button" class="btn btn-primary" name="nuker" value="Nuker"></input>
                                <input type="submit" type="button" class="btn btn-primary" name="escape" value="Escape"></input>
                                <input type="submit" type="button" class="btn btn-primary" name="jungler" value="Jungler"></input>
                            </form>
                        
                        </div>
                    
                    </div>
                    <table class="table table-striped table-condensed text-center" id="heroes">
                        {% for hero in heroes %}
                        <td padding="10px">
                        <p><input type="image" src="{% static hero.image %}" onclick="testFunc(this)" data-toggle="popover" data-trigger="hover" title="{{ hero.name }}" data-html="true" data-content="{{ hero.type }}" width="63" height="35" border="1"></src>
                        </td>
                            {% if forloop.counter|divisibleby:10 %}
                                <tr></tr>
                            {% endif %}
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Highly Rated Teams</h3>
                    </div>
                    <div class="panel-body">
                    
                    </div>
                    
                    <table class="table table-striped" id="heroes">
                        <tr>
                            <td>Team</td>
                            <td>Rating</td>
                            <td>Description</td>
                            <td>Created by</td>
                        </tr>    
                        {% for team in highlyRated %}
                         <tr>
                             <td><a href="{% url 'team' team.slug %}">{{ team.name }}</a></td>
                             <td><p>{{ team.votes.count }}</p></td>
                             <td>{{ team.description }}</td>
                             <td><a href="{% url 'user' team.user.username %}">{{ team.user.username }}</a></td>
                         </tr> 
                        {% endfor %}  
                    </table>
                
                    
                </div>
            </div>
            
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Recently Created Teams</h3>
                    </div>
                    <div class="panel-body">
                    
                    </div>
                    <table class="table table-striped" id="heroes">
                        <tr>
                            <td>Team</td>
                            <td>Rating</td>
                            <td>Description</td>
                            <td>Created by</td>
                        </tr>    
                        {% for team in recentlyCreated %}
                         <tr>
                             <td><a href="{% url 'team' team.slug %}">{{ team.name }}</a></td>
                             <td><p>{{ team.votes.count }}</p></td>
                             <td>{{ team.description }}</td>
                             <td><a href="{% url 'user' team.user.username %}">{{ team.user.username }}</a></td>
                         </tr> 
                        {% endfor %}  
                    </table>
                </div>
            </div>
        </div>
{% endblock %}

templates/teampicker/search.html
{% extends 'teampicker/base.html' %}
{% load staticfiles %}

{% block title %}Dota 2 Team Picker - Search{% endblock %}

{% block body_block %}

    <br>
    
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-4 col-md-offset-4">
                <form action="#" method="GET">
                    
                    <div class="input-group input-group-lg">
                    <input type="text" class="form-control" name="q" placeholder="{{ query }}">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">Go!</button>
                    </span>
                    </div>
                </form>
            </div>
        </div>
        
        <br>
        <br>
        
        <div class="row">
            
            <div class="col-md-4 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Users</h3>
                    </div>
                    <div class="panel-body">
                        
                    </div>
                    
                    <table class="table table-striped" id="heroes">

                        {% for user in users %}
                         <tr>
                             <td><a href="{% url 'user' user.username %}">{{ user.username }}</a></td>
                             
                             
                         </tr> 
                        {% endfor %}  
                    </table>
                </div>
            </div>        
            
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Teams</h3>
                    </div>
                    <div class="panel-body">
                        
                    </div>
                    
                    <table class="table table-striped" id="heroes">

                        {% for team in teams %}
                         <tr>
                             <td><a href="{% url 'team' team.slug %}">{{ team.name }}</a></td>
                             
                             
                         </tr> 
                        {% endfor %}  
                    </table>
                </div>
            </div>        
            
        </div>
    </div>
{% endblock %}